# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: calypsonet-theme
  theme_night:
  font: 'calypsonet-font'
  font_size: M

# SEO

marketing:
  seo:
    site_type: Project
    local_business_type: ''
    org_name: 'Calypso Networks Association'
    description: 'Ticketing Terminal APIs.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '&copy; 2021-{year} Calypso Networks Association. All Rights Reserved.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '2006-01-02'
  time_format: '15:04'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    theme_light: github-dark
    theme_dark: github-dark
    extra_languages:
      - java
      - groovy
      - xml
      - kotlin
      - cpp
      - gradle
      - ini
      - make
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/calypsonet/calypsonet-terminal-api-website'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Custom JS extension
plugins_js: ['custom']

# custom variables
terminal_api_version:
  reader_api: '2.1.0'
  card_api: '2.0.1'
  calypso_card_api: '2.2.0'
  calypso_legacysam_api: '1.0.0'
  calypso_crypto_symmetric_api: '0.1.1'
  calypso_crypto_asymmetric_api: '0.2.0'
  storagecard_api: '1.0.0'
